@startuml

class Configuration {
  -Configuration* instance
  -bool isMaster
  -bool pusher
  -WorkpieceType[3] configuredWorkpieceOrder
  -int calOffset
  -int adcIncPerMillimeter
  +Configuration getInstance()
  +readConfig(std::string configFilePath)
  +bool systemIsMaster()
  +bool pusherUsed()
  +WorkpieceType[] getDesiredOrder()
  +saveCalibration(int offset, int flatHeight)
  +float convertAdcToMillimeter(int adcValue)
}

@enduml