@startuml
interface IEventManager {
  -int channelId
  +void sendEvent(int eventCode)
}

interface IWatchdog {
  +void notify_HeartbeatReceived()
}

interface ILogic {
  +void notify_LbStartBlocked()
}

enum WorkpieceType {
  TYPE_A
  TYPE_B
  TYPE_C
}

interface IWorkpieceManager {
  -WorkpieceType[] expectedOrder
  -WorkpieceType lastType
  +bool isInOrder(WorkpieceType type)
}

IWorkpieceManager o- WorkpieceType

@enduml