//
// Created by domxs on 17.04.2023.
//

// Used for interrupts and "thread control"
ESTRING(PULSE_STOP_THREAD)
ESTRING(PULSE_ADC_SAMPLING_DONE)
ESTRING(PULSE_INTR_ON_PORT0)

// Sensors -> MainFSM (Buttons and EStop events)
ESTRING(START_M_SHORT)
ESTRING(START_M_LONG)
ESTRING(STOP_M_SHORT)
ESTRING(RESET_M_SHORT)
ESTRING(RESET_M_LONG)
ESTRING(START_S_SHORT)
ESTRING(START_S_LONG)
ESTRING(STOP_S_SHORT)
ESTRING(RESET_S_SHORT)
ESTRING(RESET_S_LONG)
ESTRING(ESTOP_M_PRESSED)
ESTRING(ESTOP_M_RELEASED)
ESTRING(ESTOP_S_PRESSED)
ESTRING(ESTOP_S_RELEASED)

// ErrorFSM/EStoppFSM/Standby -> MotorFSM - Motor stop requests (data=0: clear
// flag, data=1: set flag)
ESTRING(MOTOR_M_STOP_REQ)
ESTRING(MOTOR_S_STOP_REQ)

// Running (within MainFSM) -> MotorFSM - Motor start requests (data=0: clear
// flag, data=1: set flag)
ESTRING(MOTOR_M_RIGHT_REQ)
ESTRING(MOTOR_S_RIGHT_REQ)

// HeightFSM -> MotorFSM - Motor slow requests (data=0: clear flag, data=1: set
// flag)
ESTRING(MOTOR_M_SLOW_REQ)
ESTRING(MOTOR_S_SLOW_REQ)

// MotorFSM -> Actuators - Commands to let the motor run fast/slow or stop
ESTRING(MOTOR_M_STOP)
ESTRING(MOTOR_M_SLOW)
ESTRING(MOTOR_M_FAST)
ESTRING(MOTOR_S_STOP)
ESTRING(MOTOR_S_SLOW)
ESTRING(MOTOR_S_FAST)

// Events to control the switch (data=0: let pass, data=1: sort out)
ESTRING(SORT_M_OUT)
ESTRING(SORT_S_OUT)

// Actuators - control lamps (off/on/flashing slow/flashing fast)
// attach one of the enum values of LampState (defined in events.h) to
// event.data to set the desired state
ESTRING(LAMP_M_GREEN)
ESTRING(LAMP_M_YELLOW)
ESTRING(LAMP_M_RED)
ESTRING(LAMP_S_GREEN)
ESTRING(LAMP_S_YELLOW)
ESTRING(LAMP_S_RED)
ESTRING(LED_M_START)
ESTRING(LED_M_RESET)
ESTRING(LED_M_Q1)
ESTRING(LED_M_Q2)
ESTRING(LED_S_START)
ESTRING(LED_S_RESET)
ESTRING(LED_S_Q1)
ESTRING(LED_S_Q2)

// Light Barriers Events
ESTRING(LBA_M_BLOCKED)
ESTRING(LBA_M_UNBLOCKED)
ESTRING(LBW_M_BLOCKED)
ESTRING(LBW_M_UNBLOCKED)
ESTRING(LBE_M_BLOCKED)
ESTRING(LBE_M_UNBLOCKED)
ESTRING(LBR_M_BLOCKED)
ESTRING(LBR_M_UNBLOCKED)
ESTRING(LBA_S_BLOCKED)
ESTRING(LBA_S_UNBLOCKED)
ESTRING(LBW_S_BLOCKED)
ESTRING(LBW_S_UNBLOCKED)
ESTRING(LBE_S_BLOCKED)
ESTRING(LBE_S_UNBLOCKED)
ESTRING(LBR_S_BLOCKED)
ESTRING(LBR_S_UNBLOCKED)

// HeightSensor -> MainFSM (Type of workpiece detected)
// Average height must be attached to event.data
ESTRING(HM_M_WS_UNKNOWN)
ESTRING(HM_M_WS_F)
ESTRING(HM_M_WS_OB)
ESTRING(HM_M_WS_BOM)
ESTRING(HM_S_WS_UNKNOWN)
ESTRING(HM_S_WS_F)
ESTRING(HM_S_WS_OB)
ESTRING(HM_S_WS_BOM)

// Calibration commands for HeightSensor
ESTRING(HM_M_CAL_OFFSET)
ESTRING(HM_M_CAL_REF)
ESTRING(HM_S_CAL_OFFSET)
ESTRING(HM_S_CAL_REF)

// Metal Sensor
ESTRING(MD_M_PAYLOAD)
ESTRING(MD_S_PAYLOAD)

// Modes
ESTRING(MODE_STANDBY)
ESTRING(MODE_RUNNING)
ESTRING(MODE_SERVICE)
ESTRING(MODE_ESTOP)
ESTRING(MODE_ERROR)

// Error occurred / solved
ESTRING(ERROR_M_SELF_SOLVABLE)
ESTRING(ERROR_M_MAN_SOLVABLE)
ESTRING(ERROR_M_SELF_SOLVED)
ESTRING(ERROR_S_SELF_SOLVABLE)
ESTRING(ERROR_S_MAN_SOLVABLE)
ESTRING(ERROR_S_SELF_SOLVED)

ESTRING(HAL_PUSHER_MOUNTED)

// Watchdog
ESTRING(WD_CONN_ESTABLISHED)
ESTRING(WD_CONN_LOST)
ESTRING(WD_CONN_REESTABLISHED)
ESTRING(WD_M_HEARTBEAT)   // Heartbeat FBM1 -> FBM2
ESTRING(WD_S_HEARTBEAT)   // Heartbeat FBM2 -> FBM1
