//
// Created by domxs on 17.04.2023.
//

// Used for interrupts and "thread control"
ESTRING(PULSE_STOP_THREAD)
ESTRING(PULSE_ADC_SAMPLING_DONE)
ESTRING(PULSE_INTR_ON_PORT0)

// Buttons and EStop
ESTRING(START_M_SHORT)
ESTRING(START_M_LONG)
ESTRING(STOP_M_SHORT)
ESTRING(RESET_M_SHORT)
ESTRING(START_S_SHORT)
ESTRING(START_S_LONG)
ESTRING(STOP_S_SHORT)
ESTRING(RESET_S_SHORT)
ESTRING(ESTOP_M_PRESSED)
ESTRING(ESTOP_S_PRESSED)
ESTRING(ESTOP_M_RELEASED)
ESTRING(ESTOP_S_RELEASED)

// Events for MotorFSM to set flags
ESTRING(MOTOR_M_SET_STOP)
ESTRING(MOTOR_M_SET_SLOW)
ESTRING(MOTOR_M_SET_FAST)
ESTRING(MOTOR_S_SET_STOP)
ESTRING(MOTOR_S_SET_SLOW)
ESTRING(MOTOR_S_SET_FAST)
// Events where Actuators are subscribed to and lets the motor immediately run fast/slow/stop
ESTRING(MOTOR_M_STOP)
ESTRING(MOTOR_M_SLOW)
ESTRING(MOTOR_M_FAST)
ESTRING(MOTOR_S_STOP)
ESTRING(MOTOR_S_SLOW)
ESTRING(MOTOR_S_FAST)

// Actuators
ESTRING(HALgelbeLampeAn)
ESTRING(HALgelbeLampeAus)
ESTRING(HALgrueneLampeAn)
ESTRING(HALgrueneLampeAus)
ESTRING(HALroteLampeAn)
ESTRING(HALroteLampeAus)
ESTRING(WARNING_M)
ESTRING(WARNING_S)
ESTRING(LED_M_START)
ESTRING(LED_M_RESET)
ESTRING(LED_M_Q1)
ESTRING(LED_M_Q2)
ESTRING(LED_S_START)
ESTRING(LED_S_RESET)
ESTRING(LED_S_Q1)
ESTRING(LED_S_Q2)

// Light Barriers
ESTRING(LBA_M_BLOCKED)
ESTRING(LBA_S_BLOCKED)
ESTRING(LBA_M_UNBLOCKED)
ESTRING(LBA_S_UNBLOCKED)
ESTRING(LBW_M_BLOCKED)
ESTRING(LBW_S_BLOCKED)
ESTRING(LBW_M_UNBLOCKED)
ESTRING(LBW_S_UNBLOCKED)
ESTRING(LBE_M_BLOCKED)
ESTRING(LBE_S_BLOCKED)
ESTRING(LBE_M_UNBLOCKED)
ESTRING(LBE_S_UNBLOCKED)
ESTRING(LBR_M_BLOCKED)
ESTRING(LBR_S_BLOCKED)
ESTRING(LBR_M_UNBLOCKED)
ESTRING(LBR_S_UNBLOCKED)

// HeightSensor
ESTRING(HM_M_WS_UNKNOWN)
ESTRING(HM_M_WS_F)
ESTRING(HM_M_WS_OB)
ESTRING(HM_M_WS_BOM)
ESTRING(HM_S_WS_UNKNOWN)
ESTRING(HM_S_WS_F)
ESTRING(HM_S_WS_OB)
ESTRING(HM_S_WS_BOM)

// Metal Sensor
ESTRING(MD_M_PAYLOAD)
ESTRING(MD_S_PAYLOAD)

// Modes
ESTRING(MODE_STANDBY)
ESTRING(MODE_RUNNING)
ESTRING(MODE_SERVICE)
ESTRING(MODE_ESTOP)
ESTRING(MODE_ERROR)

// Watchdog
ESTRING(WatchDogHeartbeat)
ESTRING(WatchDogHeartbeatTimeOut)
